- name: Install EPEL release for nginx
  yum: name=epel-release state=present

- name: Install nginx web server
  yum: name=nginx state=installed update_cache=true
  notify:
      - start nginx

- file: path=/etc/nginx/conf.d state=directory

- name: copy default.conf
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf

- name: install  apache
  yum: name=httpd state=installed update_cache=true
  notify:
      - start apache

- name: configure apache to listen on 8080
  lineinfile:
          path: /etc/httpd/conf/httpd.conf
          regexp: '^Listen '
          insertafter: '^#Listen '
          line: 'Listen 0.0.0.0:8080'

- name: Set DocumentRoot
  lineinfile:
          path: /etc/httpd/conf/httpd.conf
          regexp: '^DocumentRoot '
          insertafter: '^#DocumentRoot '
          line: 'DocumentRoot "{{DocumentRoot}}" '

- name: check if httpd.conf is already modified 
  shell: grep "AllowOverride All" /etc/httpd/conf/httpd.conf
  register: apache
  ignore_errors: yes

- name: Set AllowOverrride
  replace:
          path: /etc/httpd/conf/httpd.conf
          regexp: 'AllowOverride none'
          replace: 'AllowOverride All'
  when: apache.rc == 1

- name: Set AllowOverrride
  replace:
          path: /etc/httpd/conf/httpd.conf
          regexp: 'Require all denied'
          replace: ' '
  when: apache.rc == 1

- name: Copy index.html
  template: src=index.html dest={{DocumentRoot}}

- name: start apache
  service: name=httpd state=restarted

- name: start nginx
  service: name=nginx state=restarted
