- name: create tomcat group
  group: name="{{ tomcat_group }}" state=present

- name: Create tomcat user if missing 
  user: name="{{ tomcat_user }}" password=* createhome=no system=yes state=present group={{tomcat_group}}

- name: download the tomcat tar file
  get_url: url=https://archive.apache.org/dist/tomcat/{{tomcat_v}}/{{t_version}}/bin/{{tar_file}}.tar.gz dest=/tmp/{{tar_file}}.tar.gz

- name: unarchive tar file
  unarchive: src="/tmp/{{tar_file}}.tar.gz" dest=/tmp

- name: creat homdir
  file: path="{{home_dir}}" state=directory   owner={{ tomcat_user }} group={{tomcat_group}}

- name: move files to {{home_dir}}
  shell: " mv /tmp/{{tar_file}}/* {{home_dir}} " 

- name: change ownership
  file: path="{{home_dir}}"  owner={{ tomcat_user }} group={{tomcat_group}} recurse=yes

- name: copy the service file
  template: src=tomcat.service dest=/etc/systemd/system/tomcat.service

- name: reload systemd
  command: systemctl daemon-reload

- name: start activemq
  service: name=tomcat state=started

- name: deploy the war
  copy: src="{{role_path}}/files/{{war_file}}" dest={{home_dir}}/webapps/{{war_file}} remote_src=yes owner={{ tomcat_user }} group={{tomcat_group}}
